#define __IT___
#define __IT_STRCPY__
#define __IT_PRINTF__
#define __IT_INPORTW__
#define __IT_INPORTB_P__
#define __IT_OUTPORTW_P__
#define __IT_AIUTO__
#define __IT_INPORTB__
#define __IT_MALLOC__
#define __IT_OUTPORTB__
#define __IT_EXEC__
#define __IT__START__
#define __IT_STRSTR__
#define __IT_SSCANF__
#define __IT_SPACCA__
#define __IT_MAIN__
#define __IT_GETCHAR__
#define __IT_GET_SCR_POS__
#define __IT_OUTPORTW__
#define __IT__END__
#define __IT_SH_GETS__
#define __IT_STRLEN__
#define __IT_OUTPORTB_P__
#define __IT_FREE__
