#!/bin/bash

echo "FORMATTO IL FLOPPY ..."
echo " "
mkfs.ext2 /dev/fd0
echo " "

echo "COMPILO e CREO L' IMMAGINE..."
echo " "

nasm -fbin boot/bewoot.asm -o boot/bewoot.bin
gcc  -fomit-frame-pointer -O   -nostdlib  -march=i386 -nostdinc -I./include -c -o main.o main.c
gcc  -fomit-frame-pointer -O   -nostdlib  -march=i386 -nostdinc -I./include -c -o functions/printk.o functions/printk.c
gcc  -fomit-frame-pointer -O   -nostdlib  -march=i386 -nostdinc -I./include -c -o interrupt/idt.o interrupt/idt.c
gcc  -fomit-frame-pointer -O   -nostdlib  -march=i386 -nostdinc -I./include -c -o functions/io_port.o functions/io_port.c
gcc  -fomit-frame-pointer -O   -nostdlib  -march=i386 -nostdinc -I./include -c -o interrupt/pic8259.o interrupt/pic8259.c
gcc  -fomit-frame-pointer -O   -nostdlib  -march=i386 -nostdinc -I./include -c -o functions/keyboard.o functions/keyboard.c
gcc  -fomit-frame-pointer -O   -nostdlib  -march=i386 -nostdinc -I./include -c -o functions/string.o functions/string.c
gcc  -fomit-frame-pointer -O   -nostdlib  -march=i386 -nostdinc -I./include -c -o functions/shell.o functions/shell.c


#gcc  -fomit-frame-pointer -O   -Wall  -nostdlib  -march=i386 -nostdinc -I./include -c -o main.o main.c
#gcc  -fomit-frame-pointer -O   -Wall  -nostdlib  -march=i386 -nostdinc -I./include -c -o functions/printk.o functions/printk.c
#gcc  -fomit-frame-pointer -O   -Wall  -nostdlib  -march=i386 -nostdinc -I./include -c -o interrupt/idt.o interrupt/idt.c
#gcc  -fomit-frame-pointer -O   -Wall  -nostdlib  -march=i386 -nostdinc -I./include -c -o functions/io_port.o functions/io_port.c
#gcc  -fomit-frame-pointer -O   -Wall  -nostdlib  -march=i386 -nostdinc -I./include -c -o interrupt/pic8259.o interrupt/pic8259.c
#gcc  -fomit-frame-pointer -O   -Wall  -nostdlib  -march=i386 -nostdinc -I./include -c -o functions/keyboard.o functions/keyboard.c
#gcc  -fomit-frame-pointer -O   -Wall  -nostdlib  -march=i386 -nostdinc -I./include -c -o functions/string.o functions/string.c
#gcc  -fomit-frame-pointer -O   -Wall  -nostdlib  -march=i386 -nostdinc -I./include -c -o functions/shell.o functions/shell.c




ld  -Bstatic --oformat binary  -o kernel.bin main.o functions/printk.o interrupt/idt.o functions/io_port.o interrupt/pic8259.o functions/keyboard.o  functions/string.o functions/shell.o -Ttext 0x10000 -Map kernel.map
cat boot/bewoot.bin  kernel.bin > BeWos.img

echo " "
echo "SCRITTURA IMMAGINE SU FLOPPY..."
echo " "

dd if=/home/black/Desktop/BeWos/BeWos.img of=/dev/fd0



