#!/bin/bash
numero=` ls -al kernel.bin | colrm 1 37 | colrm 6`
len=`expr $numero / 512  + 1`
echo "KRNL_SIZE	equ	 $len	  ; Kernel size in sectors, starts at sector 2" > boot/kernel_len.inc
echo $len > fs/len_kernel.txt
