#ifndef _SYSCALL_H_
#define  _SYSCALL_H_

enum {      
	SYS_ALLOC = 1, 
	SYS_FREE, //2
	SYS_REALLOC, //3
	SYS_CALLOC,//4
	SYS_PUTC,//5
	SYS_PUTS,//6
	SYS_SETTXTCOLOR,//7
	SYS_SETBACKCOLOR,//8
	SYS_GETTXTCOLOR,//9
	SYS_GETBACKCOLOR,//10
	SYS_GETSCRPOS,//11
	SYS_GETC,//12
	SYS_GETS,//13
	SYS_ENABLEIRQ,//14
	SYS_DISABLEIRQ,//15
	SYS_KBHIT,//16
	SYS_EXEC,//17
	SYS_READ_ENV_VAR,//18
	SYS_WRITE_ENV_VAR,//19
	SYS_ADD_INTERRUPT, //20
	LIBC_VSPRINTF=100,
	LIBC_VSSCANF,
        SYS_READ_BLOCK,
        SYS_WRITE_BLOCK,
        SYS_EXEC_CCC,
	SYS_FLOPPY_R_BUFF,
	SYS_FLOPPY_W_BUFF,
};

void init_syscall();

#endif
