
BS_OEMName db ' RVæÅË('
BPB_BytsPerSec dw 24065
BPB_SecPerClus db 191
BPB_RsvdSecCnt dw 33272
BPB_NumFATs db 102
BPB_RootEntCnt dw 11659
BPB_TotSec16 dw 32131
BPB_Media db 4
BPB_FATSz16 dw  3840
BPB_SecPerTrk dw 51844
BPB_NumHeads  dw 32768
BPB_HiddSec dd 1946222460
BPB_TotSec32 dd 495674942
BS_DrvNum db 102
BS_Reserved1 db 49
BS_BootSig db 192
BS_VolId dd 71645567
BS_VolLab db 'ãE)Ef'
BS_FileSysType db 'D\fDDÕ'
