#!/bin/bash

#Script per l'emulazione di MatrixOS tramite BOCHS

echo "		+---------------------------------------+"
echo "		|	  	MatrixOS Make		|"
echo "		+---------------------------------------+"
echo "		|	->Build	& Install & Test	|"
echo "		+---------------------------------------+"
echo ""
echo ""

# Elimino i file bin
rm rm -f bin/*.bin
# Elimino i file img
rm rm -f bin/*.img
# Elimino i file oggetto
rm -f src/kernel/*.o #TODO: Da modificare
rm -f src/kernel/*~ #TODO: Da modificare

#Compilo MatrixOS
./build

#Eseguo BOCHS
bochs -f bochsrc