#!/bin/bash

#Script per compilare MatrixOS

#Compilazione del boot loader di DreamOS
#echo "Compilo il boot loader Dream Catcher"
#nasm -f bin src/boot/dreamcatcherdef.asm -o bin/boot.bin

#Compilazione del boot loader di DreamOS con il supporto per la modalità grafica.
#echo "Compilo il boot loader Dream Catcher. VBE"
#nasm -f bin src/boot/dreamcatcherdefVBE.asm -o bin/boot.bin

#Compilazione del boot loader di MatrixOS
echo "Compilo il boot loader Matrix Loader"
nasm -f bin src/boot/MatrixLoader.asm  -o bin/boot.bin
echo ""

#Compilazione del boot loader di MatrixOS con il supporto per la modalità grafica.
#echo "Compilo il boot loader Matrix Loader. VBE"
#nasm -f bin src/boot/MatrixLoaderVBE.asm  -o bin/boot.bin
#echo ""

echo "Compilo il kernel"
cd src/kernel

rm -f main.o gdt.o idt.o inthandler.o irq.o string.o string++.o stdlib.o video.o bochsdebug.o keyboard.o keytraslation.o pit.o vbe.o physicalmem.o virtualmem.o stringutil.o kout.o klog.o kdbg.o kerr.o kshell.o

g++ -nostdlib -fomit-frame-pointer -Wall -march=i386 -fno-builtin -fno-exceptions -fno-rtti -I./header -I./header/libc -I./header/libc++ -c -o main.o main.cpp

gcc -nostdlib -fomit-frame-pointer -Wall -march=i386 -fno-builtin -fno-exceptions -fno-rtti -I./header -I./header/libc -I./header/libc++ -c -o gdt.o hardware/cpu/gdt.cpp

gcc -nostdlib -fomit-frame-pointer -Wall -march=i386 -fno-builtin -fno-exceptions -fno-rtti -I./header -I./header/libc -I./header/libc++ -c -o idt.o hardware/cpu/idt.cpp

gcc -nostdlib -fomit-frame-pointer -Wall -march=i386 -fno-builtin -fno-exceptions -fno-rtti -I./header -I./header/libc -I./header/libc++ -c -o inthandler.o hardware/cpu/inthandler.cpp

gcc -nostdlib -fomit-frame-pointer -Wall -march=i386 -fno-builtin -fno-exceptions -fno-rtti -I./header -I./header/libc -I./header/libc++ -c -o irq.o hardware/cpu/irq.cpp

gcc -nostdlib -fomit-frame-pointer -Wall -march=i386 -fno-builtin -fno-exceptions -fno-rtti -I./header -I./header/libc -I./header/libc++ -c -o string.o libc/string.cpp

gcc -nostdlib -fomit-frame-pointer -Wall -march=i386 -fno-builtin -fno-exceptions -fno-rtti -I./header -I./header/libc -I./header/libc++ -c -o stdlib.o libc/stdlib.cpp

gcc -nostdlib -fomit-frame-pointer -Wall -march=i386 -fno-builtin -fno-exceptions -fno-rtti -I./header -I./header/libc -I./header/libc++ -c -o string++.o libc++/string.cpp

gcc -nostdlib -fomit-frame-pointer -Wall -march=i386 -fno-builtin -fno-exceptions -fno-rtti -I./header -I./header/libc -I./header/libc++ -c -o video.o hardware/driver/video.cpp

gcc -nostdlib -fomit-frame-pointer -Wall -march=i386 -fno-builtin -fno-exceptions -fno-rtti -I./header -I./header/libc -I./header/libc++ -c -o keyboard.o hardware/driver/keyboard.cpp

gcc -nostdlib -fomit-frame-pointer -Wall -march=i386 -fno-builtin -fno-exceptions -fno-rtti -I./header -I./header/libc -I./header/libc++ -c -o keytraslation.o hardware/driver/keytraslation.cpp

gcc -nostdlib -fomit-frame-pointer -Wall -march=i386 -fno-builtin -fno-exceptions -fno-rtti -I./header -I./header/libc -I./header/libc++ -c -o bochsdebug.o hardware/driver/bochsdebug.cpp

gcc -nostdlib -fomit-frame-pointer -Wall -march=i386 -fno-builtin -fno-exceptions -fno-rtti -I./header -I./header/libc -I./header/libc++ -c -o pit.o hardware/driver/pit.cpp

gcc -nostdlib -fomit-frame-pointer -Wall -march=i386 -fno-builtin -fno-exceptions -fno-rtti -I./header -I./header/libc -I./header/libc++ -c -o vbe.o hardware/driver/vbe.cpp

gcc -nostdlib -fomit-frame-pointer -Wall -march=i386 -fno-builtin -fno-exceptions -fno-rtti -I./header -I./header/libc -I./header/libc++ -c -o physicalmem.o memory/physicalmem.cpp

gcc -nostdlib -fomit-frame-pointer -Wall -march=i386 -fno-builtin -fno-exceptions -fno-rtti -I./header -I./header/libc -I./header/libc++ -c -o virtualmem.o memory/virtualmem.cpp

gcc -nostdlib -fomit-frame-pointer -Wall -march=i386 -fno-builtin -fno-exceptions -fno-rtti -I./header -I./header/libc -I./header/libc++ -c -o stringutil.o kframework/stringutil.cpp

gcc -nostdlib -fomit-frame-pointer -Wall -march=i386 -fno-builtin -fno-exceptions -fno-rtti -I./header -I./header/libc -I./header/libc++ -c -o kout.o kservices/kout.cpp
gcc -nostdlib -fomit-frame-pointer -Wall -march=i386 -fno-builtin -fno-exceptions -fno-rtti -I./header -I./header/libc -I./header/libc++ -c -o klog.o kservices/klog.cpp
gcc -nostdlib -fomit-frame-pointer -Wall -march=i386 -fno-builtin -fno-exceptions -fno-rtti -I./header -I./header/libc -I./header/libc++ -c -o kdbg.o kservices/kdbg.cpp
gcc -nostdlib -fomit-frame-pointer -Wall -march=i386 -fno-builtin -fno-exceptions -fno-rtti -I./header -I./header/libc -I./header/libc++ -c -o kerr.o kservices/kerr.cpp

gcc -nostdlib -fomit-frame-pointer -Wall -march=i386 -fno-builtin -fno-exceptions -fno-rtti -I./header -I./header/libc -I./header/libc++ -c -o kshell.o kservices/kshell.cpp

ld -Bstatic --oformat binary -o../../bin/kernel.bin main.o gdt.o idt.o inthandler.o irq.o string.o string++.o stdlib.o video.o bochsdebug.o keyboard.o keytraslation.o pit.o vbe.o physicalmem.o virtualmem.o stringutil.o kout.o klog.o kdbg.o kerr.o kshell.o -Ttext 0x10000 -Map kernel.map

cd ../..
echo ""

echo "Scrivo l'immagine del floppy disk"
cat bin/boot.bin bin/kernel.bin > bin/Floppy.img
echo ""
