#define __IT___
#define __IT_GCC2_COMPILED.__
#define __IT_GCC2_COMPILED.__
#define __IT_STRCPY__
#define __IT_PRINTF__
#define __IT_GETENV__
#define __IT_MARCA__
#define __IT_FGETS__
#define __IT_MEMCPY__
#define __IT_FEOF__
#define __IT_MALLOC__
#define __IT_KBHIT__
#define __IT_CREAENTRY__
#define __IT_READ_BLOCK__
#define __IT_FORMAT_L__
#define __IT_PATH_TO_NUM__
#define __IT_FSEEK__
#define __IT__START__
#define __IT_STRSTR__
#define __IT_LEGGIFILE__
#define __IT_LEGGICHAR__
#define __IT_STRNCMP__
#define __IT_CERCACLUST__
#define __IT_SSCANF__
#define __IT_SETFAT12__
#define __IT_FREAD__
#define __IT_SPACCA__
#define __IT_FOPEN__
#define __IT_MEMSET__
#define __IT_MAIN__
#define __IT_FTELL__
#define __IT_SALVABUF__
#define __IT_FCLOSE__
#define __IT_GETCHAR__
#define __IT_WRITE_BLOCK__
#define __IT_STRCMP__
#define __IT_FWRITE__
#define __IT_EDITA__
#define __IT_FORMAT_S__
#define __IT_CANCFILE__
#define __IT_STRLEN__
#define __IT_CARICABUF__
#define __IT_SETTA_DISK__
#define __IT_VISUAL__
#define __IT_INTFAT12__
#define __IT_FREE__
