#!/bin/bash
numero=` ls -al kernel/kernel.bin | colrm 1 35 | colrm 9`
len=`expr $numero / 512  + 1`

echo " la lunghezza dek kernel è $len " 

numeron=` ls -al ccs/ccs.bin | colrm 1 35 | colrm 9`

lenn=`expr $numeron / 512  +  1`
lenn=`expr $lenn / 2 + $lenn`

echo " la lunghezza del ccs è $lenn" 

vlen=` expr $len + $lenn + 2`

echo " la lunghezza totale è $vlen"

echo "KRNL_SIZE	equ	 $vlen	  ; Kernel size in sectors, starts at sector 2" > boot/kernel_len.inc



